project:
  type: website
  output-dir: docs
  # this line creates a place to hold our html files
  # can delete the file that gets made automatically ("_site")

website:
  title: "jalva459.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - What I'm reading

format:
  html:
    theme:
      light: Brite
      dark: Darkly
    css: styles.css
    toc: true



